#!/usr/bin/env python3
"""Build the game's post list (docs/posts.js) from data/topics/iran.json.

Run after topics.py. Drops reposts, posts containing links, very short posts,
and duplicate texts.

Usage: python3 build_game_data.py
"""
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent
SOURCE = ROOT / "data" / "topics" / "iran.json"
OUT = ROOT / "docs" / "posts.js"

URL = re.compile(r"https?://\S+")
MIN_TEXT_CHARS = 15


def main():
    posts = json.loads(SOURCE.read_text())
    seen = set()
    game = []
    dropped = {"repost": 0, "has link": 0, "too short": 0, "duplicate": 0}
    for p in posts:  # oldest first, so duplicates keep their first appearance
        if p["is_repost"]:
            dropped["repost"] += 1
            continue
        if URL.search(p["text"]):
            dropped["has link"] += 1
            continue
        if len(p["text"]) < MIN_TEXT_CHARS:
            dropped["too short"] += 1
            continue
        key = " ".join(p["text"].lower().split())
        if key in seen:
            dropped["duplicate"] += 1
            continue
        seen.add(key)
        game.append({"d": p["created_at"], "t": p["text"], "u": p["url"]})

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("// Generated by build_game_data.py. Do not edit.\nwindow.POSTS = "
                   + json.dumps(game, ensure_ascii=False) + ";\n")
    print(f"{len(game)} playable posts -> {OUT.relative_to(ROOT)} ({OUT.stat().st_size // 1024} KB)")
    print("dropped: " + ", ".join(f"{v} {k}" for k, v in dropped.items()))


if __name__ == "__main__":
    main()
