#!/usr/bin/env python3
"""Build the game's post list (docs/posts.js) from data/topics/iran.json.

Run after topics.py. Drops reposts, posts containing links, very short posts,
headers whose content was an image ("OFFICIAL STATEMENT OF IRAN:"), and
duplicates, including corrected re-posts ("Gigiorgia" -> "Giorgia"), where the
later version is kept. Only posts listed in data/labels/iran_deals.json (deals
and ceasefires) go into the game.

Usage: python3 build_game_data.py
"""
import json
import re
from difflib import SequenceMatcher
from pathlib import Path

ROOT = Path(__file__).resolve().parent
SOURCE = ROOT / "data" / "topics" / "iran.json"
OUT = ROOT / "docs" / "posts.js"
DEALS = ROOT / "data" / "labels" / "iran_deals.json"

URL = re.compile(r"https?://\S+")
MIN_TEXT_CHARS = 15
NEAR_DUP_RATIO = 0.9
NEAR_DUP_WINDOW = 14 * 24 * 60 * 60  # seconds
EXTENDED_MIN_CHARS = 200  # a re-post that adds to a post at least this long


def normalize(text):
    return " ".join(text.lower().split())


def near_duplicate(a, b):
    """True for a corrected re-post, or a re-post with text added to the end."""
    m = SequenceMatcher(None, a, b, autojunk=False)
    if m.ratio() >= NEAR_DUP_RATIO:
        return True
    shorter = min(len(a), len(b))
    covered = sum(block.size for block in m.get_matching_blocks())
    return shorter >= EXTENDED_MIN_CHARS and covered / shorter >= 0.95


def post_id(p):
    return p["url"].rsplit("/", 1)[1]


def seconds(p):
    from datetime import datetime
    return datetime.fromisoformat(p["created_at"].replace("Z", "+00:00")).timestamp()


def main():
    posts = json.loads(SOURCE.read_text())
    deal_ids = set(json.loads(DEALS.read_text())["ids"])
    kept = []
    dropped = {"repost": 0, "has link": 0, "too short / image header": 0, "duplicate": 0}
    for p in posts:  # oldest first, so duplicates keep their first appearance
        if p["is_repost"]:
            dropped["repost"] += 1
            continue
        if URL.search(p["text"]):
            dropped["has link"] += 1
            continue
        if len(p["text"]) < MIN_TEXT_CHARS or p["text"].endswith(":"):
            dropped["too short / image header"] += 1
            continue
        key = normalize(p["text"])
        dup = next((i for i, q in enumerate(kept)
                    if seconds(p) - seconds(q) < NEAR_DUP_WINDOW
                    and near_duplicate(key, normalize(q["text"]))), None)
        if dup is not None:
            # Same text, or a corrected re-post: keep the later version, but stay
            # labeled as a deal post if either version was.
            dropped["duplicate"] += 1
            if post_id(kept[dup]) in deal_ids:
                deal_ids.add(post_id(p))
            kept[dup] = p
            continue
        kept.append(p)

    game = [{"d": p["created_at"], "t": p["text"], "u": p["url"]}
            for p in kept if post_id(p) in deal_ids]

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("// Generated by build_game_data.py. Do not edit.\nwindow.POSTS = "
                   + json.dumps(game, ensure_ascii=False) + ";\n")
    print(f"{len(game)} deal & ceasefire posts (of {len(kept)} playable) -> "
          f"{OUT.relative_to(ROOT)} ({OUT.stat().st_size // 1024} KB)")
    print("dropped: " + ", ".join(f"{v} {k}" for k, v in dropped.items()))


if __name__ == "__main__":
    main()
